name: Publish Docker image
on:
  push:
    branches: main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.gc_p }}
          registry: ghcr.io
          repository: inscannr/api
          tags: ${{ github.sha }}
          dockerfile: Dockerfile
