name: Build and publish a Docker image to the GHCR

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
      REGISTRY: ghcr.io
      USER: ${{ github.actor }}
      REPOSITORY: ${{ github.repository }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
      VERSION: ${{ github.sha }}
      IP: ${{ secrets.IP }}
      HOST: ${{ secrets.HOST }}
      KNWHST: ${{ secrets.KNWHST }}
      PWD: ${{ secrets.PWD }}
      CNTNR_PRT_IN: ${{ secrets.CNTNR_PRT_IN }}
      CNTNR_PRT_OT: ${{ secrets.CNTNR_PRT_OT }}
      CNTNR_NM: ${{ secrets.CNTNR_NM }}
      CNTNR_ENV: ${{ secrets.CNTNR_ENV }}

jobs:

  build-and-push-x86-image:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image for x86 systems
        run: docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:x86-${{ env.VERSION }} .

      - name: Log in to the GHCR
        run: 
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          
      - name: Push image to the GHCR
        run: 
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:x86-${{ env.VERSION }}

  build-and-push-arm-image:
      
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build Image for arm systems
        run: docker build -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:arm-${{ env.VERSION }} -f arm-Dockerfile .
        
      - name: Log in to the GHCR
        run: 
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          
      - name: Push arm image to the GHCR
        run: 
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:arm-${{ env.VERSION }}
          
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ env.IP }}
          user: ${{ env.HOST }}
          key: ${{ env.PWD }}
          first_ssh: sudo docker rm -f ${{ env.CNTNR_NM }}
          last_ssh: sudo docker run -d -p ${{ env.CNTNR_PRT_OT }}:${{ env.CNTNR_PRT_IN }} --name ${{ env.CNTNR_NM }} ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:arm-${{ env.VERSION }}
